version: "3.8"
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5433:5433"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password